import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Home - Habitria",
  description: "Generated by create next app",
};

import Navbar from "./components/Navbar";

export default function Layout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <>
      <Navbar />
      <main>
        {children}
      </main>
    </>
  )
}