import type { Metadata } from "next";
import { Providers } from "./providers";

import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Habitria",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} bg-bg-l-100 dark:bg-bg-d-100 text-text-l-100 dark:text-text-d-100`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
